pub mod about;
mod components;

use std::sync::atomic::AtomicU64;

use topcoat::{
    Result,
    asset::{AssetBundle, RouterBuilderAssetExt},
    context::Cx,
    htmx::hx_request,
    router::{Router, RouterBuilderDiscoverExt, layout, page},
    tailwind,
    view::{component, view},
};

pub struct Counter(AtomicU64);

// The `module_router!()` macro call must be placed at the root of your route structure.
// In this case, the `app` module is marked as the root.
pub fn router() -> topcoat::router::Router {
    Router::builder()
        .discover()
        .assets(AssetBundle::load().unwrap())
        .app_context(Counter(AtomicU64::new(0)))
        // .assets(AssetBundle::load_dir("target/assets").unwrap())
        .build()
}

#[component]
async fn head() -> Result {
    view! {
        <head>
            <title>"Nono"</title>
            // Load the stylesheet generated by the Tailwind build step.
            <link rel="stylesheet" href=(tailwind::stylesheet!())>
            <script
                type="module"
                src="https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.2/bundles/datastar.js"
            ></script>
            <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js"></script>
            // <link rel="stylesheet" href=(topcoat::tailwind::stylesheet!())>
            topcoat::dev::script()
        </head>
    }
}

#[layout("/")]
async fn root_layout(cx: &Cx, slot: Result) -> Result {
    if hx_request(cx) {
        return slot;
    }

    view! {
        <!DOCTYPE html>
        <html lang="en" data-theme="sunset">
            head()
            <body hx-boost="true" class="flex flex-col min-h-screen font-sans">
                <div class="w-full">components::navbar::navbar()</div>
                (slot?)
                <div class="w-full">components::footer::footer()</div>
            </body>
        </html>
    }
}

#[page("/")]
async fn home() -> Result {
    view! {
        <div class="w-full">components::hero::hero()</div>
        <div class="w-full flex items-center justify-center p-6">
            // components::count_data::count_data()
        </div>
        <div class="w-full flex items-center justify-center p-6">
            components::count_hx::count_hx()
        </div>
        <div class="w-full flex items-center justify-center p-6">
            components::stat::stat()
        </div>
        <div class="w-full">components::carousel::carousel()</div>
    }
}
