pub mod about;
mod components;

use topcoat::{
    Result,
    asset::{AssetBundle, RouterBuilderAssetExt},
    router::{Router, RouterBuilderDiscoverExt, layout, page},
    tailwind,
    view::{component, view},
};

// The `module_router!()` macro call must be placed at the root of your route structure.
// In this case, the `app` module is marked as the root.
pub fn router() -> topcoat::router::Router {
    Router::builder()
        .discover()
        .assets(AssetBundle::load_dir("target/assets").unwrap())
        .build()
}

#[component]
async fn head() -> Result {
    view! {
        <head>
            <title>"Nono"</title>
            // Load the stylesheet generated by the Tailwind build step.
            <link rel="stylesheet" href=(tailwind::stylesheet!())>
            // <link rel="stylesheet" href=(topcoat::tailwind::stylesheet!())>
            topcoat::dev::script()
        </head>
    }
}

#[layout("/")]
async fn root_layout(slot: Result) -> Result {
    view! {
        <!DOCTYPE html>
        <html lang="en" data-theme="sunset">
            head()
            <body class="flex flex-col min-h-screen font-sans">
                // <nav>
                //                     <a href="/">"home"</a>
                //                     " | "
                //                     <a href="/about">"about"</a>
                //                     " | "
                //                     <a href="/docs">"docs"</a>
                //                     " | "
                //                     <a href="/docs/install">"install"</a>
                //                     " | "
                //                     <a href="/pricing">"pricing"</a>
                //                 </nav>
                <div class="w-full">components::navbar::navbar()</div>
                (slot?)
            </body>
        </html>
    }
}

#[page("/")]
async fn home() -> Result {
    view! {
        <div class="w-full">components::hero::hero()</div>
        <div class="w-full flex items-center justify-center p-6">
            components::stat::stat()
        </div>
        <div class="w-full">components::carousel::carousel()</div>
        <div class="w-full">components::footer::footer()</div>
    }
}
