use topcoat::{
    Result,
    asset::{AssetBundle, RouterBuilderAssetExt},
    font::fontsource::fontsource_font,
    router::{Router, RouterBuilderDiscoverExt, layout, page},
    tailwind,
    view::{component, view},
};

#[tokio::main]
async fn main() {
    topcoat::start(
        Router::builder()
            .discover()
            .assets(AssetBundle::load_dir("target/assets").unwrap())
            .build(),
    )
    .await
    .unwrap();
}

#[component]
async fn head() -> Result {
    view! {
        <head>
        <title>"Nono"</title>
        // Load the stylesheet generated by the Tailwind build step.
        topcoat::font::link(font: fontsource_font!(GEIST))
        <link rel="stylesheet" href=(tailwind::stylesheet!())>
        // <link rel="stylesheet" href=(topcoat::tailwind::stylesheet!())>
        topcoat::dev::script()
        </head>
    }
}

#[layout("/")]
async fn root_layout(slot: Result) -> Result {
    view! {
        <!DOCTYPE html>
        <html>
        head()

            // These utility classes center the page and style its background.
            <body
                class="flex min-h-screen items-center justify-center bg-slate-100 font-sans"
            >
                (slot?)
            </body>
        </html>
    }
}

#[page("/")]
async fn home() -> Result {
    view! {
        <main
                   class="mx-4 w-full max-w-md rounded-2xl bg-white p-8 shadow-lg ring-1 ring-slate-200"
               >
                   // Tailwind's `hidden` utility removes this warning, so it only
                   // appears when the generated stylesheet is missing.
                   <p class="hidden">
                       "Tailwind is not working: this page should look styled."
                   </p>

                   // The inline style hides this badge until Tailwind's important
                   // `flex!` utility overrides `display: none`.
                   <p
                       style="display: none"
                       class="flex! w-fit items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-sm font-medium text-emerald-800"
                   >
                       <span class="size-2 rounded-full bg-emerald-500"></span>
                       "Tailwind is working"
                   </p>

                   <h1 class="mt-4 text-2xl font-bold tracking-tight text-slate-900">
                       "Topcoat + Tailwind"
                   </h1>

                   <p class="mt-2 text-slate-600">
                       "Utility classes in your Rust sources are compiled into this page's stylesheet by the standalone Tailwind CLI."
                   </p>

                   <a
                       href="https://tailwindcss.com/docs"
                       class="mt-6 inline-block rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white shadow-sm hover:bg-blue-500"
                   >
                       "Read the Tailwind docs"
                   </a>
               </main>
    }
}

// #[component]
// async fn hello(name: &str) -> Result {
//     view! {
//         <h1>"Hello, " (name) "!"</h1>
//     }
// }

// #[component]
// async fn delete_card() -> Result {
//     view! {
//         card(
//             card_header(
//                 card_title("Delete workspace")
//                 card_description(
//                     "This permanently removes the workspace and all of its data."
//                 )
//             )
//             card_footer(
//                 attrs: attributes! { class="justify-end" },
//                 button(variant: ButtonVariant::Ghost, "Cancel")
//                 button(variant: ButtonVariant::Destructive, "Delete workspace")
//             )
//         )
//     }
// }
