mod components;

use components::button::button;
use components::card::{
    card, card_content, card_description, card_footer, card_header, card_title,
};
use components::input::input;
use components::label::label;

use topcoat::{
    Result,
    asset::{AssetBundle, RouterBuilderAssetExt},
    font::fontsource::fontsource_font,
    router::{Router, RouterBuilderDiscoverExt, layout, page},
    tailwind,
    view::{attributes, component, view},
};

#[tokio::main]
async fn main() {
    topcoat::start(
        Router::builder()
            .discover()
            .assets(AssetBundle::load_dir("target/assets").unwrap())
            .build(),
    )
    .await
    .unwrap();
}

#[component]
async fn head() -> Result {
    view! {
        <head>
        <title>"Nono"</title>
        // Load the stylesheet generated by the Tailwind build step.
        topcoat::font::link(font: fontsource_font!(GEIST))
        <link rel="stylesheet" href=(tailwind::stylesheet!())>
        // <link rel="stylesheet" href=(topcoat::tailwind::stylesheet!())>
        topcoat::dev::script()
        </head>
    }
}

#[layout("/")]
async fn root_layout(slot: Result) -> Result {
    view! {
        <!DOCTYPE html>
        <html>
        head()

            // These utility classes center the page and style its background.
            <body
                class="flex min-h-screen items-center justify-center bg-slate-100 font-sans"
            >
                (slot?)
            </body>
        </html>
    }
}

#[component]
async fn sign_in() -> Result {
    view! {
        card(
            card_header(
                card_title("Sign in")
                card_description("Use your work email to continue.")
            )
            card_content(
                <form class="flex flex-col gap-2">
                    label(attrs: attributes! { for="email" }, "Email")
                    input(
                        attrs: attributes! { id="email" type="email" placeholder="you@example.com" }
                    )
                </form>
            )
            card_footer(button(attrs: attributes! { class="w-full" }, "Sign in"))
        )
    }
}

#[page("/")]
async fn home() -> Result {
    view! {
        <main
                   class="mx-4 w-full max-w-md rounded-2xl bg-white p-8 shadow-lg ring-1 ring-slate-200"
               >
                   // Tailwind's `hidden` utility removes this warning, so it only
                   // appears when the generated stylesheet is missing.
                   <p class="hidden">
                       "Tailwind is not working: this page should look styled."
                   </p>

                   // The inline style hides this badge until Tailwind's important
                   // `flex!` utility overrides `display: none`.
                   <p
                       style="display: none"
                       class="flex! w-fit items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-sm font-medium text-emerald-800"
                   >
                       <span class="size-2 rounded-full bg-emerald-500"></span>
                       "Tailwind is working"
                   </p>

                   <h1 class="mt-4 text-2xl font-bold tracking-tight text-slate-900">
                       "Topcoat + Tailwind"
                   </h1>

                   sign_in()
               </main>
    }
}

// #[component]
// async fn hello(name: &str) -> Result {
//     view! {
//         <h1>"Hello, " (name) "!"</h1>
//     }
// }

// #[component]
// async fn delete_card() -> Result {
//     view! {
//         card(
//             card_header(
//                 card_title("Delete workspace")
//                 card_description(
//                     "This permanently removes the workspace and all of its data."
//                 )
//             )
//             card_footer(
//                 attrs: attributes! { class="justify-end" },
//                 button(variant: ButtonVariant::Ghost, "Cancel")
//                 button(variant: ButtonVariant::Destructive, "Delete workspace")
//             )
//         )
//     }
// }
